#! /usr/bin/env bash

#if [ "$EUID" -ne 0 ];
#then
#	echo "Please run as root"
#	exit
#fi

mount -t cifs -o user=helcone,gid=users,uid=$(whoami),forcegid,forceuid //192.168.1.4/helcone /home/user/Shares

